comment_width = 80
edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "One"
imports_granularity = "Crate"
max_width = 60
normalize_comments = true
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
version = "Two"
wrap_comments = true
